server:
  port: 8082
  servlet:
    contextPath: /sportProducts

spring:
  datasource:
    password: thibaut
    url: jdbc:mysql://localhost:3306/sports_products?user=root
    driverClassName: com.mysql.cj.jdbc.Driver