@startuml
hide circle

entity User {
    * id
    **email**
    password
    firstname
    lastname
    birth_date
    phone_number [0..1]
    city
    postal_code
    street
    house_number
}

entity Category {
    * id
    name
    label
}

entity Product  {
    * id
    price
}

entity Order {
    *id
    date
}

entity OrderProduct {
    *id
    quantity
}

entity Translation {
    * id
    french
    deutsch
    german
}

entity Promotion {
    *id
    start_date
    end_date
    percentage
}

Order ||-left-o{ OrderProduct : Content
User ||--o{ Order : Ordering
Category ||--o{ Product : Belong
OrderProduct }o--|| Product : Belong

Category }o--o| Promotion : Promotion

Product }o-left-|| Translation : Label
Product }o--|| Translation : Description
@enduml