@startuml
hide circle

entity User {
    * id
    firstname
    lastname
    birth_date
}

entity Category {
    * id
    name
    label
}

entity Product  {
    * id
    name
    label
    description
    price
}

entity Order {
    *id
    date
}

entity OrderProduct {
    *id
    quantity
}

entity Translation {
    * name
    label
}

Order ||--o{ OrderProduct : Content
User ||--o{ Order : Ordering
Category ||--o{ Product : Belong
OrderProduct }o--|| Product

Category }o--|| Translation : Labeling
Product }o--|| Translation : Labeling

@enduml