@startuml
hide circle


entity User {
    * id
    firstname
    lastname
    birth_date
}

entity Category {
    * id
    name
    label
}

entity Product  {
    * id
    category
    name
    label
    description
    price
}

entity Order {
    *id
    user
    date
}

entity OrderProduct {
    *id
    order
    product
    quantity
}

Order::user -right-> User::id
Order::id <-left- OrderProduct::order
Product::category -right-> Category::id
OrderProduct::product --> Product::id
@enduml